contact: https://www.turing.ac.uk/research/research-engineering

title: "Project management with Github"
includeleftnav: True
short: Github

defaults:
  - scope: {path: ""}
    values: {layout: default}

baseurl: /github-pm-training

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]


include:
  - "ch04packaging/greetings/doc/_static"
  - "ch04packaging/greetings/doc/_static"
  - "ch04packaging/greetings/doc/_modules"
exclude:
  - "*/*.nbconvert.ipynb"
  - "*/*.v2.ipynb"
  - "combined_files"
  - "combined.ipynb"
